name: boom-baby
favicon: null
layout_spectrum: 0.01601809519343078
typography_spectrum: 0.8242084279190749
title: boom-baby site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.3933424095157534
  lightness: 0.3125
  saturation: 0.5708657049108297
  rhythmicContrast: 1
purpose: []
